version: "3.4"
services:

  mmaker-database:
    container_name: mmaker-database
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "M0vieMak&r"
      ACCEPT_EULA: "Y"
      
  mmaker-api:
    container_name: mmaker-api
    build:
      context: ./
      args:
        ENV: development
    depends_on:
      - mmaker-database
    links:
      - mmaker-database
    ports:
      - 5001:80